#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo service nginx start