#!/usr/bin/env bash
# Not found page 404

sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start 
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
service nginx start